(OK) Loading cuda 9.0.176
(OK) Loading cudnn 7.0.5
/home/rs619065/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
load test data...
=======================================================

predicting for fold 0...

2018-12-26 15:21:24.571659: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-26 15:21:24.860756: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla P100-SXM2-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.4805
pciBusID: 0000:06:00.0
totalMemory: 15.90GiB freeMemory: 15.61GiB
2018-12-26 15:21:24.860806: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-12-26 15:21:27.245067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-26 15:21:27.245099: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-12-26 15:21:27.245107: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-12-26 15:21:27.250237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15135 MB memory) -> physical GPU (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0000:06:00.0, compute capability: 6.0)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rs619065/.local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 565, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "/home/rs619065/.local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 548, in <lambda>
    initargs=(seqs,))
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 222, in _repopulate_pool
    w.start()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

Terminated
(OK) Loading cuda 9.0.176
(OK) Loading cudnn 7.0.5
/home/rs619065/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
load test data...
=======================================================

predicting for fold 0...

2018-12-26 15:47:09.027905: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-26 15:47:09.257046: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla P100-SXM2-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.4805
pciBusID: 0000:84:00.0
totalMemory: 15.90GiB freeMemory: 15.61GiB
2018-12-26 15:47:09.257081: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-12-26 15:47:11.967353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-26 15:47:11.967382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-12-26 15:47:11.967389: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-12-26 15:47:11.967773: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15135 MB memory) -> physical GPU (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0000:84:00.0, compute capability: 6.0)
Process PoolWorker-19:
Process PoolWorker-22:
Process PoolWorker-17:
Process PoolWorker-23:
Traceback (most recent call last):
Process PoolWorker-20:
Process PoolWorker-18:
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 117, in worker
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 117, in worker
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self.run()
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 117, in worker
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 117, in worker
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 117, in worker
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 117, in worker
    put((job, i, result))
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 388, in put
    put((job, i, result))
    put((job, i, result))
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 388, in put
    put((job, i, result))
    put((job, i, result))
    wacquire()
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 388, in put
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 388, in put
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 388, in put
    put((job, i, result))
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 388, in put
KeyboardInterrupt
    wacquire()
    wacquire()
    wacquire()
    wacquire()
    wacquire()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
Process PoolWorker-24:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 113, in worker
    result = (True, func(*args, **kwds))
  File "/home/rs619065/.local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/rwthfs/rz/cluster/home/rs619065/HPAIC/src/generator.py", line 68, in __getitem__
    batch_x = self.generate_data(indexes)
  File "/rwthfs/rz/cluster/home/rs619065/HPAIC/src/generator.py", line 93, in generate_data
    img = image_augment(aug, img)
  File "/rwthfs/rz/cluster/home/rs619065/HPAIC/src/generator.py", line 17, in image_augment
    image = aug(image=image)['image']
  File "/home/rs619065/.local/lib/python2.7/site-packages/albumentations/core/transforms_interface.py", line 27, in __call__
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/rwthfs/rz/cluster/home/rs619065/HPAIC/src/utils.py", line 170, in apply
    return np.ascontiguousarray(np.rot90(img, self.factor))
  File "/home/rs619065/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 590, in ascontiguousarray
    return array(a, dtype, copy=False, order='C', ndmin=1)
KeyboardInterrupt
Traceback (most recent call last):
  File "predict.py", line 127, in <module>
    predict_test(args=arguments)
  File "predict.py", line 115, in predict_test
    verbose=args.verbose)
  File "/home/rs619065/.local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/rs619065/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1522, in predict_generator
    verbose=verbose)
  File "/home/rs619065/.local/lib/python2.7/site-packages/keras/engine/training_generator.py", line 435, in predict_generator
    generator_output = next(output_generator)
  File "/home/rs619065/.local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 595, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 548, in get
    self.wait(timeout)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 540, in wait
    self._cond.acquire()
KeyboardInterrupt
Terminated
(OK) Loading cuda 9.0.176
(OK) Loading cudnn 7.0.5
/home/rs619065/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
load training data...
=======================================================

2018-12-26 16:44:56.649850: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-26 16:44:56.895669: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla P100-SXM2-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.4805
pciBusID: 0000:06:00.0
totalMemory: 15.90GiB freeMemory: 15.61GiB
2018-12-26 16:44:56.895707: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-12-26 16:44:59.710291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-26 16:44:59.710337: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-12-26 16:44:59.710346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-12-26 16:44:59.710753: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15135 MB memory) -> physical GPU (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0000:06:00.0, compute capability: 6.0)
validate the model on 21108 samples
validate the model on 21131 samples
validate the model on 21166 samples
validate the model on 21167 samples
validate the model on 21105 samples
load test data...
=======================================================

predicting for fold 0...

predicting for fold 1...

predicting for fold 2...

predicting for fold 3...

predicting for fold 4...

Error in atexit._run_exitfuncs:Process PoolWorker-1223:

Process PoolWorker-1219:
Process PoolWorker-1220:
Process PoolWorker-1224:
Process PoolWorker-1221:
Process PoolWorker-1218:
Process PoolWorker-1217:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    func(*targs, **kargs)
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 299, in _exit_function
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 102, in worker
    _run_finalizers(0)
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 268, in _run_finalizers
    finalizer()
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 201, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 487, in _terminate_pool
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 117, in worker
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 117, in worker
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 117, in worker
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 117, in worker
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 117, in worker
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    outqueue.put(None)                  # sentinel
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 388, in put
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 117, in worker
    put((job, i, result))
    put((job, i, result))
    task = get()
    put((job, i, result))
    put((job, i, result))
    put((job, i, result))
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 388, in put
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 388, in put
KeyboardInterrupt
KeyboardInterrupt
    wacquire()
KeyboardInterrupt
KeyboardInterrupt
    put((job, i, result))
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 388, in put
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 299, in _exit_function
    _run_finalizers(0)
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 268, in _run_finalizers
    wacquire()
    finalizer()
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 201, in __call__
KeyboardInterrupt
    wacquire()
    wacquire()
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 487, in _terminate_pool
KeyboardInterrupt
KeyboardInterrupt
    outqueue.put(None)                  # sentinel
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 388, in put
    wacquire()
KeyboardInterrupt
Process PoolWorker-1222:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 117, in worker
    put((job, i, result))
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 390, in put
    return send(obj)
KeyboardInterrupt
